# Generated by Django 5.0.6 on 2024-06-26 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('CodPacient', models.AutoField(primary_key=True, serialize=False)),
                ('NumePacient', models.CharField(max_length=100)),
                ('PrenumePacient', models.CharField(max_length=100)),
                ('Adresa', models.CharField(max_length=255)),
                ('Telefon', models.CharField(max_length=15)),
                ('DataNasterii', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tratament',
            fields=[
                ('CodTratament', models.AutoField(primary_key=True, serialize=False)),
                ('Diagnoza', models.CharField(max_length=255)),
                ('DataCazarii', models.DateField()),
                ('Durata', models.IntegerField()),
                ('CodPacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionare.pacient')),
            ],
        ),
    ]
