name: CI/CD Pipeline to Azure VM

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-app:latest

      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop devops-app-container || true
            docker rm devops-app-container || true
            cd ~/devops-learning-project || git clone https://github.com/vladsandu2000000/DevOps-Learning-Project.git ~/devops-learning-project
            cd ~/devops-learning-project
            git pull origin main
            docker compose down
            docker compose up -d --build
            docker compose exec -T web python spa_salon/manage.py migrate

